Cargo.toml
README.md
src/lib.rs
src/schema_registry.rs
uml/consumer.puml
uml/producer.puml

prepare release 0.3.2

---

.gitignore
README.md
src/lib.rs
src/schema_registry.rs

Fixes a couple issues in contacting a live Confluent Schema Registry.  Also adds some minor quality-of-life improvements to some of the side-APIs.
Fixes #2 #3 #4 #6

Some QoL improvements and fixes for live Confluent Schema Registry

---

.travis.yml
Cargo.toml
README.md
RELEASE_NOTES.md
make.toml
prepare_integration_test.sh
src/lib.rs
src/schema_registry.rs
tests/integration_tests.rs
tests/kafka_consumer.rs
tests/kafka_producer.rs

prepare 1.0.0 release

---

Cargo.toml
README.md
RELEASE_NOTES.md
src/lib.rs
src/schema_registry.rs
tests/integration_tests.rs
tests/kafka_producer.rs

fixes https://github.com/gklijs/schema_registry_converter/issues
like to have something like it for the decoder as well, and need to update documentation as well.

add struct support

---

README.md
src/lib.rs
src/schema_registry.rs
tests/integration_tests.rs

fix issue https://github.com/gklijs/schema_registry_converter/issues/11

---

.travis.yml
docker-compose.yaml
make.toml
tests/integration_tests.rs
tests/kafka_consumer.rs

Add integration test to ci

---

.travis.yml
README.md

Wait for sr to be alive

---

Cargo.toml
src/avro.rs
src/lib.rs
src/proto.rs
src/proto_fish.rs
src/schema_registry.rs
tests/kafka_consumer.rs

Add proto fish (dynamic protobuf) decoder

---

Cargo.toml
src/avro.rs
src/lib.rs
src/proto_decoder.rs
src/proto_raw_encoder.rs
src/proto_resolver.rs
src/schema_registry.rs
tests/integration_tests.rs
uml/consumer.puml
uml/producer.puml

Proto proto

---

Cargo.toml
src/proto_decoder.rs
src/proto_raw_encoder.rs
src/proto_resolver.rs

Properly implement the protobuf encoding

---

Cargo.toml
src/avro.rs
src/proto_decoder.rs
src/proto_raw_encoder.rs
src/schema_registry.rs
tests/kafka_consumer.rs
tests/kafka_producer.rs

Stil wip, just replaces reqwest fro curl for now. Fixes https://github.com/gklijs/schema_registry_converter/issues/26 when merged.

Move to reqwest to handle http calls instead of curl.

---

Cargo.toml
README.md
RELEASE_NOTES.md
src/async_impl/avro.rs
src/async_impl/easy_proto_decoder.rs
src/async_impl/json.rs
src/async_impl/proto_decoder.rs
src/async_impl/proto_raw.rs
src/blocking/avro.rs
src/blocking/json.rs
src/blocking/proto_decoder.rs
src/blocking/proto_raw.rs

fixes https://github.com/gklijs/schema_registry_converter/issues/55 and set version to 2.1.0, also update dependencies.

Prepare release

---

Cargo.toml

Fixes https://github.com/gklijs/schema_registry_converter/issues/78

Remove failure dependency

---

Cargo.toml
RELEASE_NOTES.md

Dependency updates before release

---

src/async_impl/json.rs
src/async_impl/proto_decoder.rs
src/async_impl/proto_raw.rs
src/blocking/json.rs
src/blocking/proto_decoder.rs
src/blocking/proto_raw.rs
src/proto_common_types.rs
src/schema_registry_common.rs
tests/blocking/avro_consumer.rs
tests/blocking/kafka_consumer.rs
tests/blocking/proto_consumer.rs

fix for https://github.com/gklijs/schema_registry_converter/issues/87

Add additional types

---

src/async_impl/avro.rs
src/async_impl/easy_avro.rs
src/async_impl/easy_proto_decoder.rs
src/async_impl/proto_decoder.rs
src/avro_common.rs
src/blocking/avro.rs
src/blocking/proto_decoder.rs
src/proto_resolver.rs

Planned to fix both https://github.com/gklijs/schema_registry_converter/issues/86 and https://github.com/gklijs/schema_registry_converter/issues/77 and possibly something similar for json schema.

Add context when protofish is used

---

src/lib.rs
src/proto_resolver.rs
tests/lib.rs
tests/proto_resolver.rs

Fixes https://github.com/gklijs/schema_registry_converter/issues/90

Make some more things public.

---

src/blocking/json.rs

fixes https://github.com/gklijs/schema_registry_converter/issues/76

Sr validation json schema

---

Cargo.toml
README.md
src/async_impl/avro.rs
src/blocking/avro.rs
src/proto_resolver.rs
tests/blocking/kafka_consumer.rs
tests/blocking/kafka_producer.rs

Updating dependencies and fixes needed to move to new versions.

---

.github/workflows/ci.yml
Cargo.toml

Update the ci to use "docker compose" instead of "docker-compose"

Update apache-avro requirement from ^0.16 to ^0.17

---

Cargo.toml
src/async_impl/avro.rs
src/async_impl/easy_avro.rs
src/avro_common.rs

encode value

---

src/async_impl/avro.rs
src/async_impl/easy_json.rs
src/async_impl/easy_proto_decoder.rs
src/async_impl/easy_proto_raw.rs
src/async_impl/json.rs
src/async_impl/proto_decoder.rs
src/async_impl/proto_raw.rs
src/async_impl/schema_registry.rs
src/avro_common.rs
src/schema_registry_common.rs
tests/blocking/kafka_consumer.rs

Basically https://github.com/gklijs/schema_registry_converter/pull/109 without the updated git dependency.

Handle slash in subject name.

---

README.md

Just add doc for for how to use Protobuf 😃

docs(readme): add how to use Protobuf
